<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Municipio;

class MunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Definir los municipios con sus respectivos IDs de departamentos
        $municipios = [
            // Ahuachapán
            ['nombre' => 'Apaneca', 'departamento_id' => 1],
            ['nombre' => 'Atiquizaya', 'departamento_id' => 1],
            ['nombre' => 'Concepción de Ataco', 'departamento_id' => 1],
            ['nombre' => 'Guaymango', 'departamento_id' => 1],
            ['nombre' => 'Jujutla', 'departamento_id' => 1],
            ['nombre' => 'San Francisco Menéndez', 'departamento_id' => 1],
            ['nombre' => 'Tacuba', 'departamento_id' => 1],
            ['nombre' => 'Turín', 'departamento_id' => 1],
            ['nombre' => 'El Refugio', 'departamento_id' => 1],
            ['nombre' => 'Ahuachapán', 'departamento_id' => 1],
            // Cabañas
            ['nombre' => 'Ilobasco', 'departamento_id' => 2],
            ['nombre' => 'Sensuntepeque', 'departamento_id' => 2],
            ['nombre' => 'Victoria', 'departamento_id' => 2],
            ['nombre' => 'San Isidro Labrador', 'departamento_id' => 2],
            ['nombre' => 'San Juan de la Cruz', 'departamento_id' => 2],
            ['nombre' => 'San José Las Flores', 'departamento_id' => 2],
            ['nombre' => 'San Rafael Cedros', 'departamento_id' => 2],
            ['nombre' => 'Guacotecti', 'departamento_id' => 2],
            ['nombre' => 'Cinquera', 'departamento_id' => 2],
            ['nombre' => 'Cabañas', 'departamento_id' => 2],
            // Chalatenango
            ['nombre' => 'Chalatenango', 'departamento_id' => 3],
            ['nombre' => 'Arcatao', 'departamento_id' => 3],
            ['nombre' => 'La Palma', 'departamento_id' => 3],
            ['nombre' => 'Las Vueltas', 'departamento_id' => 3],
            ['nombre' => 'San Francisco Morazán', 'departamento_id' => 3],
            ['nombre' => 'San Fernando', 'departamento_id' => 3],
            ['nombre' => 'San Isidro Labrador', 'departamento_id' => 3],
            ['nombre' => 'San José Cancasque', 'departamento_id' => 3],
            ['nombre' => 'San José Las Flores', 'departamento_id' => 3],
            ['nombre' => 'San Luis del Carmen', 'departamento_id' => 3],
            //Cuscatlán
            ['nombre' => 'Cojutepeque', 'departamento_id' => 4],
            ['nombre' => 'Candelaria', 'departamento_id' => 4],
            ['nombre' => 'El Carmen', 'departamento_id' => 4],
            ['nombre' => 'El Rosario', 'departamento_id' => 4],
            ['nombre' => 'Monte San Juan', 'departamento_id' => 4],
            ['nombre' => 'Oratorio de Concepción', 'departamento_id' => 4],
            ['nombre' => 'San Bartolomé Perulapía', 'departamento_id' => 4],
            ['nombre' => 'San Cristóbal', 'departamento_id' => 4],
            ['nombre' => 'San José Guayabal', 'departamento_id' => 4],
            ['nombre' => 'San Pedro Perulapán', 'departamento_id' => 4],
            ['nombre' => 'San Rafael Cedros', 'departamento_id' => 4],
            ['nombre' => 'San Ramón', 'departamento_id' => 4],
            ['nombre' => 'Santa Cruz Michapa', 'departamento_id' => 4],
            ['nombre' => 'Suchitoto', 'departamento_id' => 4],
            ['nombre' => 'Tenancingo', 'departamento_id' => 4],
            ['nombre' => 'Tepecoyo', 'departamento_id' => 4],
            ['nombre' => 'Verapaz', 'departamento_id' => 4],
            //La Libertad
            ['nombre' => 'Santa Tecla', 'departamento_id' => 5],
            ['nombre' => 'Antiguo Cuscatlán', 'departamento_id' => 5],
            ['nombre' => 'Nuevo Cuscatlán', 'departamento_id' => 5],
            ['nombre' => 'Colón', 'departamento_id' => 5],
            ['nombre' => 'Quezaltepeque', 'departamento_id' => 5],
            ['nombre' => 'Huizúcar', 'departamento_id' => 5],
            ['nombre' => 'Comasagua', 'departamento_id' => 5],
            ['nombre' => 'Teotepeque', 'departamento_id' => 5],
            ['nombre' => 'Ciudad Arce', 'departamento_id' => 5],
            ['nombre' => 'Jayaque', 'departamento_id' => 5],
            ['nombre' => 'San José Villanueva', 'departamento_id' => 5],
            ['nombre' => 'La Libertad', 'departamento_id' => 5],
            ['nombre' => 'Santa Matilde', 'departamento_id' => 5],
            ['nombre' => 'San Juan Opico', 'departamento_id' => 5],
            ['nombre' => 'Sacacoyo', 'departamento_id' => 5],
            ['nombre' => 'San Pablo Tacachico', 'departamento_id' => 5],
            ['nombre' => 'Talnique', 'departamento_id' => 5],
            ['nombre' => 'Tamanique', 'departamento_id' => 5],
            ['nombre' => 'La Libertad', 'departamento_id' => 5],
            ['nombre' => 'Nueva San Salvador', 'departamento_id' => 5],
            ['nombre' => 'Zaragoza', 'departamento_id' => 5],
            //La Paz
            ['nombre' => 'Zacatecoluca', 'departamento_id' => 6],
            ['nombre' => 'Cuyultitán', 'departamento_id' => 6],
            ['nombre' => 'San Pedro Masahuat', 'departamento_id' => 6],
            ['nombre' => 'San Juan Nonualco', 'departamento_id' => 6],
            ['nombre' => 'San Juan Talpa', 'departamento_id' => 6],
            ['nombre' => 'San Luis La Herradura', 'departamento_id' => 6],
            ['nombre' => 'San Luis Talpa', 'departamento_id' => 6],
            ['nombre' => 'San Miguel Tepezontes', 'departamento_id' => 6],
            ['nombre' => 'San Pedro Nonualco', 'departamento_id' => 6],
            ['nombre' => 'San Rafael Obrajuelo', 'departamento_id' => 6],
            ['nombre' => 'Santa María Ostuma', 'departamento_id' => 6],
            ['nombre' => 'Santiago Nonualco', 'departamento_id' => 6],
            ['nombre' => 'Tapalhuaca', 'departamento_id' => 6],
            //La Unión
            ['nombre' => 'La Unión', 'departamento_id' => 7],
            ['nombre' => 'Concepción de Oriente', 'departamento_id' => 7],
            ['nombre' => 'Intipucá', 'departamento_id' => 7],
            ['nombre' => 'Pasaquina', 'departamento_id' => 7],
            ['nombre' => 'Chirilagua', 'departamento_id' => 7],
            ['nombre' => 'Santa Rosa de Lima', 'departamento_id' => 7],
            ['nombre' => 'Yayantique', 'departamento_id' => 7],
            ['nombre' => 'Anamorós', 'departamento_id' => 7],
            ['nombre' => 'Bolívar', 'departamento_id' => 7],
            ['nombre' => 'Meanguera del Golfo', 'departamento_id' => 7],
            ['nombre' => 'Nueva Esparta', 'departamento_id' => 7],
            //Morazán
            ['nombre' => 'San Francisco Gotera', 'departamento_id' => 8],
            ['nombre' => 'Arambala', 'departamento_id' => 8],
            ['nombre' => 'Cacaopera', 'departamento_id' => 8],
            ['nombre' => 'Chilanga', 'departamento_id' => 8],
            ['nombre' => 'Corinto', 'departamento_id' => 8],
            ['nombre' => 'Delicias de Concepción', 'departamento_id' => 8],
            ['nombre' => 'El Divisadero', 'departamento_id' => 8],
            ['nombre' => 'El Rosario', 'departamento_id' => 8],
            ['nombre' => 'Gualococti', 'departamento_id' => 8],
            ['nombre' => 'Guatajiagua', 'departamento_id' => 8],
            ['nombre' => 'Joateca', 'departamento_id' => 8],
            ['nombre' => 'Jocoaitique', 'departamento_id' => 8],
            ['nombre' => 'Jocoro', 'departamento_id' => 8],
            ['nombre' => 'Lolotiquillo', 'departamento_id' => 8],
            ['nombre' => 'Meanguera', 'departamento_id' => 8],
            ['nombre' => 'Osicala', 'departamento_id' => 8],
            ['nombre' => 'Perquín', 'departamento_id' => 8],
            ['nombre' => 'San Carlos', 'departamento_id' => 8],
            ['nombre' => 'San Fernando', 'departamento_id' => 8],
            ['nombre' => 'San Isidro', 'departamento_id' => 8],
            ['nombre' => 'San Simón', 'departamento_id' => 8],
            ['nombre' => 'Sensembra', 'departamento_id' => 8],
            ['nombre' => 'Sociedad', 'departamento_id' => 8],
            ['nombre' => 'Torola', 'departamento_id' => 8],
            ['nombre' => 'Yamabal', 'departamento_id' => 8],
            ['nombre' => 'Yoloaiquín', 'departamento_id' => 8],
            //San Miguel
            ['nombre' => 'San Miguel', 'departamento_id' => 9],
            ['nombre' => 'Carolina', 'departamento_id' => 9],
            ['nombre' => 'Chapeltique', 'departamento_id' => 9],
            ['nombre' => 'Chinameca', 'departamento_id' => 9],
            ['nombre' => 'Chirilagua', 'departamento_id' => 9],
            ['nombre' => 'Ciudad Barrios', 'departamento_id' => 9],
            ['nombre' => 'Comacarán', 'departamento_id' => 9],
            ['nombre' => 'El Tránsito', 'departamento_id' => 9],
            ['nombre' => 'Lolotique', 'departamento_id' => 9],
            ['nombre' => 'Moncagua', 'departamento_id' => 9],
            ['nombre' => 'Nueva Guadalupe', 'departamento_id' => 9],
            ['nombre' => 'Nuevo Edén de San Juan', 'departamento_id' => 9],
            ['nombre' => 'Quelepa', 'departamento_id' => 9],
            ['nombre' => 'San Antonio del Mosco', 'departamento_id' => 9],
            ['nombre' => 'San Gerardo', 'departamento_id' => 9],
            ['nombre' => 'San Jorge', 'departamento_id' => 9],
            ['nombre' => 'San Luis de la Reina', 'departamento_id' => 9],
            ['nombre' => 'San Rafael Oriente', 'departamento_id' => 9],
            ['nombre' => 'Sesori', 'departamento_id' => 9],
            ['nombre' => 'Uluazapa', 'departamento_id' => 9],
            //San Salvador
            ['nombre' => 'San Salvador', 'departamento_id' => 10],
            ['nombre' => 'Aguilares', 'departamento_id' => 10],
            ['nombre' => 'Apopa', 'departamento_id' => 10],
            ['nombre' => 'Ayutuxtepeque', 'departamento_id' => 10],
            ['nombre' => 'Cuscatancingo', 'departamento_id' => 10],
            ['nombre' => 'Delgado', 'departamento_id' => 10],
            ['nombre' => 'El Paisnal', 'departamento_id' => 10],
            ['nombre' => 'Guazapa', 'departamento_id' => 10],
            ['nombre' => 'Ilopango', 'departamento_id' => 10],
            ['nombre' => 'Mejicanos', 'departamento_id' => 10],
            ['nombre' => 'Nejapa', 'departamento_id' => 10],
            ['nombre' => 'Panchimalco', 'departamento_id' => 10],
            ['nombre' => 'Rosario de Mora', 'departamento_id' => 10],
            ['nombre' => 'San Marcos', 'departamento_id' => 10],
            ['nombre' => 'San Martín', 'departamento_id' => 10],
            ['nombre' => 'Santiago Texacuangos', 'departamento_id' => 10],
            ['nombre' => 'Santo Tomás', 'departamento_id' => 10],
            ['nombre' => 'Soyapango', 'departamento_id' => 10],
            ['nombre' => 'Tonacatepeque', 'departamento_id' => 10],
            //San Vicente
            ['nombre' => 'San Vicente', 'departamento_id' => 11],
            ['nombre' => 'Apastepeque', 'departamento_id' => 11],
            ['nombre' => 'Guadalupe', 'departamento_id' => 11],
            ['nombre' => 'San Cayetano Istepeque', 'departamento_id' => 11],
            ['nombre' => 'San Esteban Catarina', 'departamento_id' => 11],
            ['nombre' => 'San Ildefonso', 'departamento_id' => 11],
            ['nombre' => 'San Lorenzo', 'departamento_id' => 11],
            ['nombre' => 'San Sebastián', 'departamento_id' => 11],
            ['nombre' => 'Santa Clara', 'departamento_id' => 11],
            ['nombre' => 'Santo Domingo', 'departamento_id' => 11],
            ['nombre' => 'Tecoluca', 'departamento_id' => 11],
            ['nombre' => 'Tepetitán', 'departamento_id' => 11],
            ['nombre' => 'Verapaz', 'departamento_id' => 11],
            //Santa Ana
            ['nombre' => 'Santa Ana', 'departamento_id' => 12],
            ['nombre' => 'Candelaria de la Frontera', 'departamento_id' => 12],
            ['nombre' => 'Chalchuapa', 'departamento_id' => 12],
            ['nombre' => 'Coatepeque', 'departamento_id' => 12],
            ['nombre' => 'El Congo', 'departamento_id' => 12],
            ['nombre' => 'El Porvenir', 'departamento_id' => 12],
            ['nombre' => 'Masahuat', 'departamento_id' => 12],
            ['nombre' => 'Metapán', 'departamento_id' => 12],
            ['nombre' => 'San Antonio Pajonal', 'departamento_id' => 12],
            ['nombre' => 'San Sebastián Salitrillo', 'departamento_id' => 12],
            ['nombre' => 'Santa Rosa Guachipilín', 'departamento_id' => 12],
            ['nombre' => 'Santiago de la Frontera', 'departamento_id' => 12],
            ['nombre' => 'Texistepeque', 'departamento_id' => 12],
            //Sonsonate
            ['nombre' => 'Sonsonate', 'departamento_id' => 13],
            ['nombre' => 'Acajutla', 'departamento_id' => 13],
            ['nombre' => 'Armenia', 'departamento_id' => 13],
            ['nombre' => 'Caluco', 'departamento_id' => 13],
            ['nombre' => 'Cuisnahuat', 'departamento_id' => 13],
            ['nombre' => 'Izalco', 'departamento_id' => 13],
            ['nombre' => 'Juayúa', 'departamento_id' => 13],
            ['nombre' => 'Nahuizalco', 'departamento_id' => 13],
            ['nombre' => 'Nahulingo', 'departamento_id' => 13],
            ['nombre' => 'Salcoatitán', 'departamento_id' => 13],
            ['nombre' => 'San Antonio del Monte', 'departamento_id' => 13],
            ['nombre' => 'San Julián', 'departamento_id' => 13],
            ['nombre' => 'Santa Catarina Masahuat', 'departamento_id' => 13],
            ['nombre' => 'Santa Isabel Ishuatán', 'departamento_id' => 13],
            ['nombre' => 'Santo Domingo de Guzmán', 'departamento_id' => 13],
            ['nombre' => 'Sonzacate', 'departamento_id' => 13],
            //Usulután
            ['nombre' => 'Usulután', 'departamento_id' => 14],
            ['nombre' => 'Alegría', 'departamento_id' => 14],
            ['nombre' => 'Berlín', 'departamento_id' => 14],
            ['nombre' => 'California', 'departamento_id' => 14],
            ['nombre' => 'Concepción Batres', 'departamento_id' => 14],
            ['nombre' => 'El Triunfo', 'departamento_id' => 14],
            ['nombre' => 'Ereguayquín', 'departamento_id' => 14],
            ['nombre' => 'Estanzuelas', 'departamento_id' => 14],
            ['nombre' => 'Jiquilisco', 'departamento_id' => 14],
            ['nombre' => 'Jucuapa', 'departamento_id' => 14],
            ['nombre' => 'Jucuarán', 'departamento_id' => 14],
            ['nombre' => 'Mercedes Umaña', 'departamento_id' => 14],
            ['nombre' => 'Nueva Granada', 'departamento_id' => 14],
            ['nombre' => 'Ozatlán', 'departamento_id' => 14],
            ['nombre' => 'Puerto El Triunfo', 'departamento_id' => 14],
            ['nombre' => 'San Agustín', 'departamento_id' => 14],
            ['nombre' => 'San Buenaventura', 'departamento_id' => 14],
            ['nombre' => 'San Dionisio', 'departamento_id' => 14],
            ['nombre' => 'San Francisco Javier', 'departamento_id' => 14],
            ['nombre' => 'Santa Elena', 'departamento_id' => 14],
            ['nombre' => 'Santa María', 'departamento_id' => 14],
            ['nombre' => 'Santiago de María', 'departamento_id' => 14],
            ['nombre' => 'Tecapán', 'departamento_id' => 14],
            ['nombre' => 'Usulután', 'departamento_id' => 14],
        ];

     
        foreach ($municipios as $municipio) {
            Municipio::create($municipio);
        }
    }
}